### ISSUE TITLE
Should Spectrum support environments running Java 6?

### ISSUE THREAD

**Issue by greghaskins** [greghaskins/spectrum#27]
The test runner itself (everything in `src/main/java`) only uses features that are backward-compatible with Java 6. The idea was to keep Spectrum available as an option in scenarios where Java 8 isn't allowed and/or feasible (like testing Android apps and in many enterprise environments that aren't "ready" for Java 8 yet).

The specs themselves can be written in Java 6, but of course lambdas aren't available so they don't look as pretty:

```java
describe("specs using Java 6", new Block() {
  @Override
  public void run() throws Throwable {

    it("can use anonymous objects", new Block() {
        @Override
        public void run() throws Throwable {
            assertEquals(1, foo);
        }
    });
  }
});
```

I see a few choices:

1. Officially support Java 6 using anonymous objects (as above). While we don't have a Java 6 automated build to verify it (yet), I believe this will work just fine in the current state. This would mean keeping the production code in Java 6 mode.
2. Officially support Java 6 using [Retrolambda](https://github.com/orfjackal/retrolambda). This would allow us to use some of the Java 8 language features (but not APIs), while compiling to bytecode that runs on older JVMs. 
3. Forget compatibility with anything less than Java 8. This will make our development lives easier, but may eliminate the tool from consideration for some users.

---
Thoughts? Ideas?

**Comment by rkawala** [comment]
Java 8 was released two years ago, so it's certainly reasonable to go with
option 3. Not just because options 1 and 2 represent additional work, but
because they clutter the design of the code.

Android is about to get lambda support in the upcoming release. Anyone
starting a new project will use Java 8. Anyone stuck on older versions of
Java, likely because they don't have tests in the first place, is probably
not going to adopt Spectrum anyway.

The test runner itself (everything in src/main/java) only uses features
that are backward-compatible with Java 6. The idea was to keep Spectrum
available as an option in scenarios where Java 8 isn't allowed and/or
feasible (like testing Android apps and in many enterprise environments
that aren't "ready" for Java 8 yet).

The specs themselves can be written in Java 6, but of course lambdas aren't
available so they don't look as pretty:

describe("specs using Java 6", new Block() {
  @Override
  public void run() throws Throwable {

    it("can use anonymous objects", new Block() {
        @Override
        public void run() throws Throwable {
            assertEquals(1, foo);
        }
    });
  }
});

I see a few choices:

   1. Officially support Java 6 using anonymous objects (as above). While
   we don't have a Java 6 automated build to verify it (yet), I believe this
   will work just fine in the current state. This would mean keeping the
   production code in Java 6 mode.
   2. Officially support Java 6 using Retrolambda
   <https://github.com/orfjackal/retrolambda>. This would allow us to use
   some of the Java 8 language features (but not APIs), while compiling to
   bytecode that runs on older JVMs.

3. Forget compatibility with anything less than Java 8. This will make our
development lives easier, but may eliminate the tool from consideration for
some users.

Thoughts? Ideas?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/greghaskins/spectrum/issues/27>

**Comment by greghaskins** [comment]
@rkawala good point about Android. You're referring to [Android N](https://en.wikipedia.org/wiki/Android_N) right? It looks like after that is released, life gets a lot easier for Android devs.

I'm not sure what to do about web devs stuck on older Java versions. For one, I don't think an old Java version implies teams don't write tests. I have been on several teams stuck on old JVM versions like WAS for whatever reason, but we still test-drove our code. A lot of bigger companies are very slow to adopt newer versions of the JVM. It's hard to find stats online, but at least a couple different places [[1]](https://dzone.com/articles/java-version-statistics-2015) [[2]](http://www.baeldung.com/java-8-adoption-march-2016) show a sizeable group of developers not yet on Java 8.

I know many library projects (e.g. Commons, Spring, Guava, etc.) maintain backward-compatibility for just that reason, and they certainly write lots of unit tests. Requiring `sourceCompatibility = 1.8` with Spectrum would mean library authors using it would also have to require Java 8 (at least to run their own test suite). [This article about Spring compatibility](https://spring.io/blog/2015/04/03/how-spring-achieves-compatibility-with-java-6-7-and-8) was interesting.

That said, there might still be enough reasons to drop pre-1.8 support:
- Spectrum tests really should be written with lambdas. If you can't use them, it pretty much defeats the point of the library.
- We could use streams and other good bits from the latest Java 8 standard library, not to mention lambdas on the production side of the library.
- More simplicity in building and supporting the library, since there are fewer possible edge cases that could crop up across JVM versions. No need to maintain a separate suite of Java-6-compatible tests for Spectrum or anything like that.
- There's a precedent in many cases where tests can run newer/different Java versions, even if production code has to be Java 6. Heck, even the [Spring Framework build.gradle](https://github.com/spring-projects/spring-framework/blob/1f9a9cf404e452cf25fbe21931e0b35ef61dff1f/build.gradle#L115-L124) uses this technique.

I guess after that wandering line of thought, I'm leaning towards supporting only Java 8 (and newer). **Anyone have a strong opinion in support of backwards compatibility?**

Spectrum will probably have one more mid-size internal refactor before `1.0`, so it would be good to have this settled in the next week or so. Dropping Java 6 support would be a [semver](http://semver.org/) major change, although we're still in `0.x.y` "initial development" mode at the moment.

**Comment by kotse** [comment]
I know you asked for strong opinion in support of backwards compatibility, but this is so true we need to repeat it:
> Spectrum tests really should be written with lambdas. If you can't use them, it pretty much defeats the point of the library.

If something is not easy to do, people just do not use it. If there was no Java 8, would you write spectrum? I don't think so - JUnit will be much less verbose, even if it does not let you document your tests like spectrum's BDD style does.

**Comment by greghaskins** [comment]
Good points, all.

It sounds like it's settled: Spectrum will require Java 8 to run tests. Our implementation will assume that minimum, both for syntax and the standard library. 

Users may use Spectrum to test production code that is pre-1.8, of course, but their test scope would require a Java 8 compiler and JVM.
