### ISSUE TITLE
Create official documentation page/site

### ISSUE THREAD

**Issue by greghaskins** [greghaskins/spectrum#39]
To include:
- More examples and detail than is relevant in README
- IDE snippets for auto-completing `describe`, `it`, etc.
- Suggested usage with tools like Mockito
- Patterns for writing clean specs (helper functions, etc.)
- Links to binaries, GitHub, repo, and contributor list

For simplicity, I'll probably set this up with GitHub Pages and some sort of static HTML generator with a pre-made template.

**Comment by greghaskins** [comment]
This will be really helpful, but shouldn't block the `1.0.0` release.

**Comment by richdouglasevans** [comment]
Greg, do you have any strong preference about the tooling used to generate the documentation? (Jekyll, Pelican, etc?)

I'd like to pick this task up by focusing on writing the actual documentation in Markdown, with the generation done a wee bit later once there's some actual content; perhaps someone could smash down the tooling and plug it into the build in a separate development activity?

Unless anyone says otherwise, I'll throw down an overview of the various chapters later this week with an eye to cracking them out.

**Comment by greghaskins** [comment]
I am most familiar with Jekyll, but do not have a strong preference. Simple updates and deployment will win. I'm a fan of Markdown.

Splitting the writing and tooling sounds like a good idea. If you get some basic docs put together, we can spin up a separate task for the infrastructure/etc. to make those accessible.

**Comment by greghaskins** [comment]
Closing #39, as we've got a decent-enough solution in place for now. We can open a new issue for future improvements.
