### ISSUE TITLE
Support a Given/When/Then declaration syntax

### ISSUE THREAD

**Issue by greghaskins** [greghaskins/spectrum#50]
A feature request from @ashleyfrieze. It would be cool to be able to declare specs with a syntax similar to Cucumber.

This could either be a Spectrum add-on like [rspec-given](https://github.com/jimweirich/rspec-given) is for RSpec or the beginnings of [multiple interfaces like in Mocha](https://mochajs.org/#interfaces).

**Comment by ashleyfrieze** [comment]
The end-game of this for me is:

- Make it easy to use Feature/Scenario/Given/When/Then/And to structure specs
  - Note: this means that the lowest unit of this Gherkin-style spec is actually a step, not an independent spec as it is with the describe/it syntax
- Treat the execution of Given/When/Then/And as a single spec, so any failure will apply to all steps within the parent
- Allow for the sharing of test execution state between steps - this is pretty much essential, since the Then step is usually asserting the outcome of executing a Then step - so it needs to be able to probe the result of Then
- Make it easy to selectively run features and scenarios:
  - This probably means a bigger mechanism than the ignore/focus that's presently done within Spectrum
  - For non-trivial situations, this also probably means allowing for tagging of nodes in the tree
  - If there's tagging, then there needs to be a mechanism for selecting the tag
  - The selection mechanism needs to be available at development time and also at CI time
  - Duplicating Cucumber's tag feature is not a perfect solution, but the solution should be a cousin of that
- Optional: it might be nice to be able to output pure Gherkin from Spectrum. In fact, it might be nice to be able to render Spectrum in more than just the JUnit runner UI and surefire/failsafe/etc reports.

**Comment by ashleyfrieze** [comment]
Now you've merged #51 does this close?

**Comment by greghaskins** [comment]
Closed by #51.
